# Generated by Django 4.0.5 on 2022-08-05 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Diretores',
            },
        ),
        migrations.CreateModel(
            name='Filme_exibido_sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Sala dos filmes exibidos',
            },
        ),
        migrations.CreateModel(
            name='Filme_has_premiacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganhou', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Filmes Premiados',
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Funções',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('carteiraTrabalho', models.IntegerField()),
                ('dataContratacao', models.DateField()),
                ('salario', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Gêneros',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Horários',
            },
        ),
        migrations.CreateModel(
            name='Premiacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('ano', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Premiações',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('capacidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Horario_trab_func',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='prova02.funcao')),
            ],
            options={
                'verbose_name_plural': 'Horários de trabalho dos funcionários',
            },
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeBR', models.CharField(max_length=45)),
                ('nomeEN', models.CharField(max_length=45)),
                ('anoLancamento', models.IntegerField()),
                ('sinopse', models.TextField()),
                ('diretor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='prova02.diretor')),
                ('genero', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='prova02.genero')),
            ],
        ),
    ]
